name: temiajiboye
description: A basic pure-dart web app with ssr & automatic client hydration.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  jaspr: ^0.9.0
  jaspr_riverpod: ^0.3.6

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^2.1.0
jaspr:
  uses-ssr: false
